name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - env:
            MY_SECRET: ${{ secrets.MY_SECRET }}
        - run: echo "my secret is $MY_SECRET" > toto.txt
        - uses: actions/upload-artifact@v4
          with:
            name: toto
            path: toto.txt
