name: secrets test
run-name: testing secrets
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: prod
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
    steps:
        - run: echo "my secret is $MY_SECRET" > toto.txt
        - uses: actions/upload-artifact@v4
          with:
            name: toto
            path: toto.txt
